### ISSUE TITLE
Orange County, NY

### ISSUE THREAD

**Issue by iandees** [openaddresses/openaddresses#2285]
http://ocgis.orangecountygov.com/ArcGIS/rest/services/Dynamic/LandBase/MapServer/0

(For https://twitter.com/mrejfox/status/811945914067718144)

**Comment by nvkelso** [comment]
Related: https://github.com/openaddresses/openaddresses/issues/1987

**Comment by trescube** [comment]
Getting the following error processing this sourc: 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/openaddr/process_one.py", line 58, in process
    cache_result = cache(temp_src, temp_dir, extras)
  File "/usr/local/lib/python3.4/dist-packages/openaddr/__init__.py", line 106, in cache
    downloaded_files = task.download(source_urls, workdir, data.get('conform'))
  File "/usr/local/lib/python3.4/dist-packages/openaddr/cache.py", line 402, in download
    row[X_FIELDNAME] = round(centroid.x, 7)
  File "/usr/local/lib/python3.4/dist-packages/shapely/geometry/point.py", line 56, in x
    return self.coords[0][0]
IndexError: list index out of range
```

I think this means that the geometry for a record in ESRI is borked and the machine doesn't reject the record.

**Comment by iandees** [comment]
`machine` is [supposed to have defenses against that](https://github.com/openaddresses/machine/blob/allow_xml_filetype_for_gml/openaddr/cache.py#L388). Can you file a ticket in machine and I'll take a look in the morning?

**Comment by trescube** [comment]
Will do
