### ISSUE TITLE
Scioto County, Ohio Parcels

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2512]
https://www.sciotocountyengineer.org/arcgis/rest/services/OneView/ParcelsSearch/MapServer/0

![scioto_parcels](https://cloud.githubusercontent.com/assets/5324316/22783799/677539f4-ee9b-11e6-9371-cedbb609d430.jpg)

**Comment by trescube** [comment]
Got this error in both the machine and pyesridump:

```
2017-02-09 09:23:37,822 - cli.esridump - INFO - Source does not support feature count
Traceback (most recent call last):
  File "/Users/stephenhess/git/trescube/pyesridump/esridump/bin/esri2geojson", line 11, in <module>
    load_entry_point('esridump', 'console_scripts', 'esri2geojson')()
  File "/Users/stephenhess/git/trescube/pyesridump/esridump/cli.py", line 100, in main
    feature = next(feature_iter)
  File "/Users/stephenhess/git/trescube/pyesridump/esridump/dumper.py", line 248, in __iter__
    oid_field_name = self._find_oid_field_name(metadata)
  File "/Users/stephenhess/git/trescube/pyesridump/esridump/dumper.py", line 133, in _find_oid_field_name
    for f in metadata['fields']:
KeyError: 'fields'
```

**Comment by nvkelso** [comment]
In southern Ohio east of Cincinnati by a bit.
