### ISSUE TITLE
us-wi-green_lake

### ISSUE THREAD

**Issue by ingalls** [openaddresses/openaddresses#324]
```
{
    "coverage": {
        "country": "us",
        "state": "wi",
        "county": "Green Lake"
    },
    "data": "http://gis.co.green-lake.wi.us/gisweb/GIS_Viewer/asp/proxy.ashx?http://gis.co.green-lake.wi.us:8399/arcgis/rest/services/PARCEL/MapServer/4",
    "type": "ESRI",
    "note": "error"
}
```
Esri dump error @iandees 

```
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Transform.emit (events.js:74:15)
    at Request._callback (/home/unknown/Developement/openaddresses/openaddresses-cache/node_modules/openaddresses-download/node_modules/esri-dump/index.js:41:24)
    at Request.self.callback (/home/unknown/Developement/openaddresses/openaddresses-cache/node_modules/openaddresses-download/node_modules/request/request.js:121:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/unknown/Developement/openaddresses/openaddresses-cache/node_modules/openaddresses-download/node_modules/request/request.js:978:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/unknown/Developement/openaddresses/openaddresses-cache/node_modules/openaddresses-download/node_modules/request/request.js:929:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
```

**Comment by slibby** [comment]
added and tracked here: https://github.com/openaddresses/openaddresses/blob/master/sources/us/wi/green_lake.json
