### ISSUE TITLE
us-va-hanover

### ISSUE THREAD

**Issue by ingalls** [openaddresses/openaddresses#332]
```
{
    "coverage": {
        "country": "us",
        "state": "va",
        "county": "Hanover"
    },
    "data": "http://www.hanovercountygis.org/Hanover/hanover/proxy.ashx?http://pc61198svmh/ArcGIS/rest/services/Hanover/Buildings/MapServer/0",
    "type": "ESRI",
    "website": "http://www.hanovercountygis.org/Hanover/hanover/"
}
```

ESRI dump error

```
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Transform.emit (events.js:74:15)
    at Request._callback (/home/unknown/Developement/openaddresses/openaddresses-cache/node_modules/openaddresses-download/node_modules/esri-dump/index.js:41:24)
    at Request.self.callback (/home/unknown/Developement/openaddresses/openaddresses-cache/node_modules/openaddresses-download/node_modules/request/request.js:121:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/unknown/Developement/openaddresses/openaddresses-cache/node_modules/openaddresses-download/node_modules/request/request.js:978:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/unknown/Developement/openaddresses/openaddresses-cache/node_modules/openaddresses-download/node_modules/request/request.js:929:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
```

**Comment by ingalls** [comment]
Closing as stale - we have a statewide layer.
