### ISSUE TITLE
fix broken issue Warren County, Ohio

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#3795]
broken link:
http://results.openaddresses.io/sources/us/oh/warren

new data:http://www.co.warren.oh.us/warrengis/Downloads.aspx

comes in fgdb - let me know if you want a shapefile export

new terms:
Terms
The provider makes no warranty or representation with respect to this information, its quality or suitability for a particular purpose. This information is provided AS IS, and the requester assumes the entire risk as to its quality and suitability.

The provider will not be liable for direct, indirect, incidental, or consequential damages resulting from any defect in the information.

The provider shall have no liability for any other information, programs or data used with or combined with the requested information, including the cost of recovering information, programs or data.

**Comment by trescube** [comment]
Hmm... that's currently what the data url is set to, I think there's something else wrong:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/openaddr/__init__.py", line 180, in conform
    csv_path, addr_count = task4.convert(data, decompressed_paths, workdir)
  File "/usr/local/lib/python3.4/dist-packages/openaddr/conform.py", line 599, in convert
    rc = conform_cli(source_definition, source_path, dest_path)
  File "/usr/local/lib/python3.4/dist-packages/openaddr/conform.py", line 1299, in conform_cli
    extract_to_source_csv(source_definition, source_path, extract_path)
  File "/usr/local/lib/python3.4/dist-packages/openaddr/conform.py", line 1246, in extract_to_source_csv
    ogr_source_to_csv(source_definition, ogr_source_path, extract_path)
  File "/usr/local/lib/python3.4/dist-packages/openaddr/conform.py", line 666, in ogr_source_to_csv
    _L.info("Converting layer %s to CSV", repr(in_layer.GetName()))
AttributeError: 'NoneType' object has no attribute 'GetName'
```

**Comment by stefanb** [comment]
It seems that the layer "ADDRESS_POINTS" defined in 
https://github.com/openaddresses/openaddresses/blob/master/sources/us/oh/warren.json#L19
is no longer present in the gdb:
```
$ ogrinfo ParcelsAndRoads.gdb
Had to open data source read-only.
INFO: Open of `ParcelsAndRoads.gdb'
      using driver `OpenFileGDB' successful.
1: Tag (None)
2: Warren_Boundaries (Multi Line String)
3: Warren_Parcels (Multi Polygon)
4: Warren_Survey_Poly (Multi Polygon)
5: Warren_Sub_Poly (Multi Polygon)
6: Political_Subdivision_Poly (Multi Polygon)
7: Parcel_Point (Point)
8: Warren_Annexations (Multi Polygon)
9: ConveyanceParcels (Multi Polygon)
10: PLSS_VMS_POLY (Multi Polygon)
11: RightOfWayPoly (Multi Polygon)
12: Declarations (Multi Polygon)
13: T_1_DirtyAreas (Multi Polygon)
14: T_1_PointErrors (Point)
15: T_1_LineErrors (Multi Line String)
16: T_1_PolyErrors (Multi Polygon)
17: Roads (Multi Line String)
```
Will try with "Parcel_Point" layer and see what happens...

**Comment by stefanb** [comment]
Using the "Parcel_Point" layer an adjusting conform to the best of my knowledge (see PR #3980) ended with error:
> Invalid number of points in LinearRing found 3 - must be 0 or >= 4

Full log in https://s3.amazonaws.com/data.openaddresses.io/runs/405262/output.txt
