### ISSUE TITLE
Error to generate Brasilia/BR state files

### ISSUE THREAD

**Issue by RodSilvaSantos** [openaddresses/openaddresses#5105]
Many errors are being presented in this data: http://results.openaddresses.io/sources/br/df/statewide
You can't download the data for that. The archives have not been updated since 2017-10-02.

The errors we are getting are:

`2020-06-26 21:10:24,671 WARNING: Error in process_one.process()
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/openaddr/process_one.py", line 134, in process
cache_result = cache(layer + '-' + data_source['name'], data_source, temp_dir, extras)
File "/usr/local/lib/python3.5/dist-packages/openaddr/init.py", line 97, in cache
downloaded_files = task.download(source_urls, workdir, data_source.get('conform'))
File "/usr/local/lib/python3.5/dist-packages/openaddr/cache.py", line 367, in download
metadata = downloader.get_metadata()
File "/usr/local/lib/python3.5/dist-packages/esridump/dumper.py", line 112, in get_metadata
metadata_json = self._handle_esri_errors(response, "Could not retrieve layer metadata")
File "/usr/local/lib/python3.5/dist-packages/esridump/dumper.py", line 59, in _handle_esri_errors
response.text,
esridump.errors.EsriDownloadError: Could not retrieve layer metadata: HTTP 503

**Comment by iandees** [comment]
Thanks for letting us know the layer is broken. It looks like they changed the base URL to https://www.geoservicos.segeth.df.gov.br/server/rest/services/, but I don't see anything that looks like address data in there. Are you able to see anything that looks like address data?

**Comment by RodSilvaSantos** [comment]
Unfortunately I don't see it. I found the old url: http://www.geoservicos.segeth.df.gov.br/ArcGIS/rest/services/Operational/LOTE/MapServer/0

It is blocked but the page's msg allows you to request access by telling the application you need access and the reason.

![image](https://user-images.githubusercontent.com/32973720/87617955-03b68c80-c6ef-11ea-8bf2-65dc6c84303d.png)
