### ISSUE TITLE
Document `first_non_empty` attribute function 

### ISSUE THREAD

**Issue by rbrtmrtn** [openaddresses/openaddresses#6425]
Noticed there's a `first_non_empty` [attribute function](https://github.com/openaddresses/batch-machine/blob/master/openaddr/conform.py#L1020) that isn't mentioned in the [docs](https://github.com/openaddresses/openaddresses/blob/master/ATTRIBUTE_FUNCTIONS.md), just making a note here.

**Comment by stefanb** [comment]
Also the pre-commit validation isn't passing.

**Comment by stefanb** [comment]
https://batch.openaddresses.io/job/353102 failed with:
````        
ok - updating job: 353102 with {"status":"Running","version":"1.1.0","output":{"cache":false,"output":false,"preview":false,"validated":false},"loglink":"batch-prod-job/default/04db52cc23f0491aabf4e537f94ff5f9"}
[{"instancePath":"/layers/addresses/0/conform/street","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/0/oneOf/0/type","keyword":"type","params":{"type":"string"},"message":"must be string"},{"instancePath":"/layers/addresses/0/conform/street","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/0/oneOf/1/type","keyword":"type","params":{"type":"array"},"message":"must be array"},{"instancePath":"/layers/addresses/0/conform/street","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/0/oneOf","keyword":"oneOf","params":{"passingSchemas":null},"message":"must match exactly one schema in oneOf"},{"instancePath":"/layers/addresses/0/conform/street","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/1/required","keyword":"required","params":{"missingProperty":"field"},"message":"must have required property 'field'"},{"instancePath":"/layers/addresses/0/conform/street","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/1/required","keyword":"required","params":{"missingProperty":"pattern"},"message":"must have required property 'pattern'"},{"instancePath":"/layers/addresses/0/conform/street","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/1/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"fields"},"message":"must NOT have additional properties"},{"instancePath":"/layers/addresses/0/conform/street/function","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/1/properties/function/enum","keyword":"enum","params":{"allowedValues":["regexp"]},"message":"must be equal to one of the allowed values"},{"instancePath":"/layers/addresses/0/conform/street","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/2/required","keyword":"required","params":{"missingProperty":"field"},"message":"must have required property 'field'"},{"instancePath":"/layers/addresses/0/conform/street","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/2/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"fields"},"message":"must NOT have additional properties"},{"instancePath":"/layers/addresses/0/conform/street/function","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/2/properties/function/enum","keyword":"enum","params":{"allowedValues":["postfixed_street"]},"message":"must be equal to one of the allowed values"},{"instancePath":"/layers/addresses/0/conform/street","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/3/required","keyword":"required","params":{"missingProperty":"field"},"message":"must have required property 'field'"},{"instancePath":"/layers/addresses/0/conform/street","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/3/required","keyword":"required","params":{"missingProperty":"field_to_remove"},"message":"must have required property 'field_to_remove'"},{"instancePath":"/layers/addresses/0/conform/street","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/3/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"fields"},"message":"must NOT have additional properties"},{"instancePath":"/layers/addresses/0/conform/street/function","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/3/properties/function/enum","keyword":"enum","params":{"allowedValues":["remove_prefix"]},"message":"must be equal to one of the allowed values"},{"instancePath":"/layers/addresses/0/conform/street","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/4/required","keyword":"required","params":{"missingProperty":"field"},"message":"must have required property 'field'"},{"instancePath":"/layers/addresses/0/conform/street","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/4/required","keyword":"required","params":{"missingProperty":"field_to_remove"},"message":"must have required property 'field_to_remove'"},{"instancePath":"/layers/addresses/0/conform/street","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/4/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"fields"},"message":"must NOT have additional properties"},{"instancePath":"/layers/addresses/0/conform/street/function","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/4/properties/function/enum","keyword":"enum","params":{"allowedValues":["remove_postfix"]},"message":"must be equal to one of the allowed values"},{"instancePath":"/layers/addresses/0/conform/street/function","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/5/properties/function/enum","keyword":"enum","params":{"allowedValues":["join"]},"message":"must be equal to one of the allowed values"},{"instancePath":"/layers/addresses/0/conform/street","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/6/required","keyword":"required","params":{"missingProperty":"format"},"message":"must have required property 'format'"},{"instancePath":"/layers/addresses/0/conform/street/function","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/6/properties/function/enum","keyword":"enum","params":{"allowedValues":["format"]},"message":"must be equal to one of the allowed values"},{"instancePath":"/layers/addresses/0/conform/street","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/7/required","keyword":"required","params":{"missingProperty":"variable"},"message":"must have required property 'variable'"},{"instancePath":"/layers/addresses/0/conform/street","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/7/required","keyword":"required","params":{"missingProperty":"functions"},"message":"must have required property 'functions'"},{"instancePath":"/layers/addresses/0/conform/street","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/7/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"fields"},"message":"must NOT have additional properties"},{"instancePath":"/layers/addresses/0/conform/street/function","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/7/properties/function/enum","keyword":"enum","params":{"allowedValues":["chain"]},"message":"must be equal to one of the allowed values"},{"instancePath":"/layers/addresses/0/conform/street","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/8/required","keyword":"required","params":{"missingProperty":"field"},"message":"must have required property 'field'"},{"instancePath":"/layers/addresses/0/conform/street","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/8/required","keyword":"required","params":{"missingProperty":"index"},"message":"must have required property 'index'"},{"instancePath":"/layers/addresses/0/conform/street","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/8/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"fields"},"message":"must NOT have additional properties"},{"instancePath":"/layers/addresses/0/conform/street/function","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/8/properties/function/enum","keyword":"enum","params":{"allowedValues":["get"]},"message":"must be equal to one of the allowed values"},{"instancePath":"/layers/addresses/0/conform/street","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/9/required","keyword":"required","params":{"missingProperty":"value"},"message":"must have required property 'value'"},{"instancePath":"/layers/addresses/0/conform/street","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/9/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"fields"},"message":"must NOT have additional properties"},{"instancePath":"/layers/addresses/0/conform/street/function","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf/9/properties/function/enum","keyword":"enum","params":{"allowedValues":["static"]},"message":"must be equal to one of the allowed values"},{"instancePath":"/layers/addresses/0/conform/street","schemaPath":"#/properties/layers/properties/addresses/items/properties/conform/properties/street/oneOf","keyword":"oneOf","params":{"passingSchemas":null},"message":"must match exactly one schema in oneOf"}]
Error: Source does not conform to V2 schema
    at Job.fetch (file:///usr/local/src/batch/lib/job.js:87:19)
    at async flow (file:///usr/local/src/batch/task.js:83:9)
ok - updating job: 353102 with {"status":"Fail"}
false
````

**Comment by iandees** [comment]
This is documented and in the schema now.

**Comment by stefanb** [comment]
The pre-commit validation succeeds, but batch is still failing, see: https://batch.openaddresses.io/run/2989

**Comment by iandees** [comment]
After adding it to the schema in this repo, we needed to (1) rev the package.json (https://github.com/openaddresses/openaddresses/commit/2a2dfb81ec8c39998904bcfae59fbf41f6251727) and (2) update the dependency in batch https://github.com/openaddresses/batch/pull/381. Those should be done now (thanks @ingalls!), so a rebuild of the PR should work.
